//
// Cost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Cost: Codable, JSONEncodable, Hashable {

    public var currency: String?
    public var value: Double?

    public init(currency: String? = nil, value: Double? = nil) {
        self.currency = currency
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

