//
// CreateMessageInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateMessageInput: Codable, JSONEncodable, Hashable {

    public var to: [String]?
    public var from: String?
    public var networkId: Int?
    public var callbackUrl: String?

    public init(to: [String]? = nil, from: String? = nil, networkId: Int? = nil, callbackUrl: String? = nil) {
        self.to = to
        self.from = from
        self.networkId = networkId
        self.callbackUrl = callbackUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case to
        case from
        case networkId = "network_id"
        case callbackUrl = "callback_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(networkId, forKey: .networkId)
        try container.encodeIfPresent(callbackUrl, forKey: .callbackUrl)
    }
}

