//
// Pricing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Pricing: Codable, JSONEncodable, Hashable {

    public var costPerUnit: Double?

    public init(costPerUnit: Double? = nil) {
        self.costPerUnit = costPerUnit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case costPerUnit = "cost_per_unit"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(costPerUnit, forKey: .costPerUnit)
    }
}

